apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-testapi
  labels:
    node_tag: testapi
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: prod-testapi
  targetCPUUtilizationPercentage: 50
