apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-testapi
  labels:
    prod_tag: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      node_tag: testapi
  template:
    metadata:
      name: testapi-pod
      labels:
        node_tag: testapi
    spec:
      containers:
        - name: prod-testapi
          image: resttestapp3acr.azurecr.io/testresrapi3:4ba88ca2f35a83c248af28eed0f808d8896a6cf7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
      imagePullSecrets:
        - name: testrestapi03
