name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: resttestapp3acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -f docker/Dockerfile -t resttestapp3acr.azurecr.io/testresrapi3:${{ github.sha }}
        docker push resttestapp3acr.azurecr.io/testresrapi3:${{ github.sha }}  
